version: '3'

services:
  veres-one:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    ports:
      - "127.0.0.1:42443:42443"
    networks:
      - app-network
  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - /tmp/veres-one-dev/mongo:/data/db
    networks:
      - app-network
  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    volumes:
      - /tmp/veres-one-dev/redis:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
