version: '3'

networks:
  dmz-network:
    driver: bridge
  app-network:
    driver: bridge

services:
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /etc/veres-one-testnet/certbot/conf:/etc/letsencrypt
      - /etc/veres-one-testnet/certbot/www:/var/www/certbot
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "10m"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nginx:
    image: nginx:1-alpine
    restart: unless-stopped
    volumes:
      - /etc/veres-one-testnet/nginx:/etc/nginx
      - /etc/veres-one-testnet/certbot/conf:/etc/letsencrypt
      - /etc/veres-one-testnet/certbot/www:/var/www/certbot
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "10m"
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - dmz-network
  veres-one:
    image: veresone/capybara:3
    restart: unless-stopped
    depends_on:
      - nginx
      - certbot
      - mongo
      - redis
    volumes:
      - /etc/veres-one-testnet/configs:/etc/veres-one
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      app-network:
        aliases:
          - bedrock-app
      dmz-network:
        aliases:
          - bedrock-app
  mongo:
    image: mongo:4
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    restart: unless-stopped
    volumes:
      - /etc/veres-one-testnet/mongo:/etc/mongo
      - /var/lib/mongodb:/data/db
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - app-network
  redis:
    image: redis:5
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    volumes:
      - /etc/veres-one-testnet/redis:/usr/local/etc/redis
      - /var/lib/redis:/data
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "10m"
    networks:
      - app-network
  nodeexporter:
    image: prom/node-exporter:v0.17.0
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "10m"
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    network_mode: host
